# Generated by Django 4.0.10 on 2023-04-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicerollers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diceroll',
            name='option',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
